### ISSUE TITLE
Configuration and Completions

### ISSUE THREAD

**Issue by TrevorS** [TrevorS/linear-cli#17]
Add configuration file support and shell completions for better user experience.

### Configuration File
- [ ] Support TOML config files in standard locations
- [ ] `~/.config/linear-cli/config.toml`
- [ ] `$XDG_CONFIG_HOME/linear-cli/config.toml` 
- [ ] `.linear-cli.toml` in current directory
- [ ] Support for default values: team, assignee, format
- [ ] Command aliases support
- [ ] Config validation with helpful error messages

### Shell Completions
- [ ] Add `linear completions <shell>` command
- [ ] Support bash, zsh, fish, powershell
- [ ] Dynamic completions for issue IDs, teams, users
- [ ] Installation instructions for each shell
- [ ] Integration with package managers

## Implementation Notes
- Use `serde` and `toml` for config parsing
- Use `clap_complete` for shell completions
- Cache team/user data for dynamic completions
- Follow XDG Base Directory specification

## Example Config File
```toml
default_team = "ENG"
default_assignee = "me"
preferred_format = "table"

[aliases]
my = ["issues", "--assignee", "me"]
todo = ["issues", "--status", "todo", "--assignee", "me"]
standup = ["issues", "--team", "ENG", "--updated-after", "yesterday"]
```

## Installation Commands
```bash
# Generate completions
linear completions bash > ~/.local/share/bash-completion/completions/linear
linear completions zsh > ~/.zfunc/_linear
linear completions fish > ~/.config/fish/completions/linear.fish
```
