### ISSUE TITLE
Implement Async Trait Patterns and Streaming

### ISSUE THREAD

**Issue by TrevorS** [TrevorS/linear-cli#52]
**Priority:** P1 - High  
**Milestone:** v2.0.0  
**Depends on:** #51

## Description
Design comprehensive async API with streaming support for large datasets and concurrent operations.

## Acceptance Criteria
- [ ] Create `LinearApi` trait with async methods
- [ ] Implement streaming for paginated data
- [ ] Add concurrent operations support
- [ ] Implement circuit breaker pattern
- [ ] Add retry logic with backoff
- [ ] Support batch operations

### New Dependencies
```toml
[dependencies]
futures = "0.3"
tokio-stream = "0.1"
async-stream = "0.3"
pin-project = "1.1"
tower = { version = "0.4", optional = true }
```

### Streaming API
```rust
// Return a stream for large datasets
async fn stream_issues(
    &self,
    params: ListIssuesParams,
) -> Result<Pin<Box<dyn Stream<Item = Result<Issue, LinearError>> + Send>>, LinearError>;
```

### Circuit Breaker
```rust
pub struct CircuitBreaker {
    failure_count: AtomicU32,
    last_failure: Mutex<Option<Instant>>,
    config: CircuitBreakerConfig,
}
```
