### ISSUE TITLE
Refactor Output Module with Terminal Detection

### ISSUE THREAD

**Issue by TrevorS** [TrevorS/linear-cli#53]
**Priority:** P1 - High  
**Milestone:** v2.0.0  
**Depends on:** #49

## Description
Create a comprehensive output module with terminal capability detection, theme support, and proper formatting.

## Acceptance Criteria
- [ ] Implement terminal capabilities detection
- [ ] Add color support detection (8/256/TrueColor)
- [ ] Detect hyperlink support
- [ ] Create theme system
- [ ] Add markdown rendering support
- [ ] Implement proper Unicode handling

### New Dependencies
```toml
[dependencies]
comfy-table = "7.1"
unicode-width = "0.1"
unicode-segmentation = "1.10"
supports-color = "2.1"
terminal_size = "0.3"
console = "0.15"
```

### Terminal Detection
```rust
pub struct TerminalCapabilities {
    pub color_support: ColorSupport,
    pub hyperlink_support: bool,
    pub unicode_support: UnicodeSupport,
    pub width: Option<u16>,
    pub is_tty: bool,
}
```

### Theme System
```rust
pub static THEMES: Lazy<HashMap<&'static str, Theme>> = Lazy::new(|| {
    // Initialize built-in themes
});
```
