### ISSUE TITLE
Implement Type State Pattern for OAuth

### ISSUE THREAD

**Issue by TrevorS** [TrevorS/linear-cli#55]
**Priority:** P1 - High  
**Milestone:** v2.0.0  
**Depends on:** #48

## Description
Redesign OAuth implementation using type state pattern for compile-time safety.

## Acceptance Criteria
- [ ] Create type states: Unauthenticated, Authenticating, Authenticated
- [ ] Implement state transitions at compile time
- [ ] Add secure token storage abstraction
- [ ] Implement platform-specific token storage
- [ ] Add token refresh logic
- [ ] Use `secrecy` and `zeroize` for sensitive data

### New Dependencies
```toml
[dependencies]
oauth2 = "4.4"
secrecy = "0.8"
zeroize = "1.7"
keyring = "2.3"

[target.'cfg(target_os = "macos")'.dependencies]
security-framework = "2.9"

[target.'cfg(target_os = "linux")'.dependencies]
secret-service = "3.0"

[target.'cfg(windows)'.dependencies]
windows-sys = "0.52"
```

### Type State Design
```rust
pub struct OAuthManager<State = Unauthenticated> {
    client: oauth2::Client,
    config: OAuthConfig,
    _state: PhantomData<State>,
}

// Compile-time state transitions
impl OAuthManager<Unauthenticated> {
    pub fn begin_auth_flow(self) -> (OAuthManager<Authenticating>, AuthUrl) { }
}

impl OAuthManager<Authenticating> {
    pub async fn complete_auth_flow(self, code: String) -> Result<OAuthManager<Authenticated>> { }
}
```
