### ISSUE TITLE
Enhance Test Infrastructure

### ISSUE THREAD

**Issue by TrevorS** [TrevorS/linear-cli#56]
**Priority:** P1 - High  
**Milestone:** v2.0.0

## Description
Build comprehensive test infrastructure with builders, property testing, and better mocking.

## Acceptance Criteria
- [ ] Create test data builders with derive_builder
- [ ] Implement fixture management system
- [ ] Add property-based testing with proptest
- [ ] Create comprehensive mock service layer
- [ ] Add test helpers for common scenarios
- [ ] Implement snapshot testing for outputs

### New Dependencies
```toml
[dev-dependencies]
derive_builder = "0.12"
fake = "2.9"
proptest = "1.4"
mockall = "0.12"
rstest = "0.18"
test-case = "3.3"
criterion = "0.5"
```

### Test Builder Pattern
```rust
#[derive(Debug, Clone, Builder)]
#[builder(setter(into))]
pub struct IssueBuilder {
    #[builder(default = "self.generate_id()")]
    pub id: String,
    
    #[builder(default = "Faker.fake()")]
    pub title: String,
}
```

### Property Testing
```rust
proptest\! {
    #[test]
    fn test_issue_serialization_roundtrip(issue in arb_issue()) {
        let serialized = serde_json::to_string(&issue).unwrap();
        let deserialized: Issue = serde_json::from_str(&serialized).unwrap();
        prop_assert_eq\!(issue.id, deserialized.id);
    }
}
```
