### ISSUE TITLE
Implement Configuration Management System

### ISSUE THREAD

**Issue by TrevorS** [TrevorS/linear-cli#57]
**Priority:** P2 - Medium  
**Milestone:** v2.0.0  
**Depends on:** #49

## Description
Create layered configuration system with hot reloading and validation.

## Acceptance Criteria
- [ ] Implement layered config loading (defaults, system, user, local, env)
- [ ] Add config file validation
- [ ] Support TOML, YAML, JSON formats
- [ ] Implement config file watching with hot reload
- [ ] Add UI and API configuration sections
- [ ] Create feature flags system

### New Dependencies
```toml
[dependencies]
config = "0.13"
directories = "5.0"
notify = "6.1"
figment = { version = "0.10", optional = true }
```

### Configuration Layers
1. Default values (in code)
2. System config (`/etc/linear-cli/config.toml`)
3. User config (`~/.config/linear-cli/config.toml`)
4. Local config (`.linear-cli.toml`)
5. Environment variables (`LINEAR_*`)

### Hot Reload
```rust
pub struct ConfigWatcher {
    config: Arc<RwLock<AppConfig>>,
    _watcher: notify::RecommendedWatcher,
}
```
