### ISSUE TITLE
Add Performance Optimizations

### ISSUE THREAD

**Issue by TrevorS** [TrevorS/linear-cli#59]
**Priority:** P3 - Low  
**Milestone:** v2.1.0  
**Depends on:** All core issues

## Description
Implement various performance optimizations including string interning, zero-copy parsing, and small vector optimizations.

## Acceptance Criteria
- [ ] Implement string interning for repeated strings
- [ ] Add zero-copy deserialization where possible
- [ ] Use SmallVec for small collections
- [ ] Profile and optimize hot paths
- [ ] Consider alternative allocators
- [ ] Add compile-time optimizations

### New Dependencies
```toml
[dependencies]
string_cache = "0.8"
smallvec = "1.13"
bytes = "1.5"
indexmap = "2.1"

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
strip = true
```

### Optimizations
```rust
// String interning
pub type InternedString = DefaultAtom;

// Small vector optimization
pub type LabelList = SmallVec<[Label; 4]>;

// Zero-copy deserialization
#[derive(Deserialize)]
pub struct IssueRef<'a> {
    #[serde(borrow)]
    pub id: Cow<'a, str>,
}
```
