### ISSUE TITLE
Add Telemetry and Monitoring

### ISSUE THREAD

**Issue by TrevorS** [TrevorS/linear-cli#60]
**Priority:** P3 - Low  
**Milestone:** v2.1.0

## Description
Add comprehensive telemetry with tracing, metrics, and optional OpenTelemetry support.

## Acceptance Criteria
- [ ] Set up tracing infrastructure
- [ ] Add metrics collection
- [ ] Implement OpenTelemetry integration (optional)
- [ ] Add performance counters
- [ ] Create debug command for diagnostics
- [ ] Add opt-in anonymous usage statistics

### New Dependencies
```toml
[dependencies]
tracing-subscriber = "0.3"
metrics = "0.21"
opentelemetry = { version = "0.21", optional = true }
```

### Tracing Setup
```rust
pub fn init_telemetry() {
    tracing_subscriber::registry()
        .with(tracing_subscriber::fmt::layer())
        .with(tracing_subscriber::filter::EnvFilter::from_default_env())
        .init();
}
```
