### ISSUE TITLE
Improve Security and Cross-Platform Support

### ISSUE THREAD

**Issue by TrevorS** [TrevorS/linear-cli#61]
**Priority:** P3 - Low  
**Milestone:** v2.1.0

## Description
Enhance security measures and improve cross-platform compatibility.

## Acceptance Criteria
- [ ] Add constant-time string comparison for tokens
- [ ] Implement secure memory clearing
- [ ] Add platform-specific code paths
- [ ] Test on Windows and Linux
- [ ] Add security audit in CI
- [ ] Implement certificate pinning option

### New Dependencies
```toml
[dependencies]
subtle = "2.5"
human-panic = "1.2"
which = "6.0"
tempfile = "3.8"
fslock = "0.2"
```

### Security Enhancements
```rust
// Constant-time comparison
use subtle::ConstantTimeEq;

pub fn verify_token(provided: &[u8], expected: &[u8]) -> bool {
    provided.ct_eq(expected).into()
}
```

### Platform-Specific Code
```rust
#[cfg(target_os = "windows")]
mod windows {
    pub fn enable_ansi_support() { }
}

#[cfg(unix)]
mod unix {
    pub fn get_terminal_size() -> Option<(u16, u16)> { }
}
```
